export const countryToRegion: Record<string, string> = {
  Russia: "Europe",
  Germany: "Europe",
  France: "Europe",
  "United Kingdom": "Europe",
  Italy: "Europe",
  Spain: "Europe",
  Ukraine: "Europe",
  Poland: "Europe",
  Netherlands: "Europe",
  Belgium: "Europe",
  "Czech Republic": "Europe",
  Greece: "Europe",
  Portugal: "Europe",
  Sweden: "Europe",
  Austria: "Europe",
  Switzerland: "Europe",
  Denmark: "Europe",
  Norway: "Europe",
  Finland: "Europe",
  Ireland: "Europe",

  China: "Asia",
  India: "Asia",
  Japan: "Asia",
  "South Korea": "Asia",
  Indonesia: "Asia",
  "Saudi Arabia": "Asia",
  Iran: "Asia",
  Turkey: "Asia",
  Thailand: "Asia",
  Vietnam: "Asia",
  Malaysia: "Asia",
  Israel: "Asia",
  Pakistan: "Asia",
  Bangladesh: "Asia",
  Philippines: "Asia",

  Nigeria: "Africa",
  Ethiopia: "Africa",
  Egypt: "Africa",
  "Democratic Republic of Congo": "Africa",
  "South Africa": "Africa",
  Tanzania: "Africa",
  Kenya: "Africa",
  Algeria: "Africa",
  Sudan: "Africa",
  Morocco: "Africa",
  Uganda: "Africa",
  Ghana: "Africa",

  "United States": "Americas",
  Canada: "Americas",
  Mexico: "Americas",
  Brazil: "Americas",
  Argentina: "Americas",
  Colombia: "Americas",
  Peru: "Americas",
  Venezuela: "Americas",
  Chile: "Americas",
  Ecuador: "Americas",
  Guatemala: "Americas",
  Cuba: "Americas",
  Bolivia: "Americas",

  Australia: "Oceania",
  "New Zealand": "Oceania",
  Fiji: "Oceania",
  "Papua New Guinea": "Oceania",

  "International transport": "International",
};

export const isRegionGroup = new Set([
  "Europe",
  "Asia",
  "Africa",
  "Americas",
  "Oceania",
  "World",
  "International",
  "International aviation",
  "International shipping",
]);
